import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source in src/
*/
`;

const root = dirname(fileURLToPath(import.meta.url));
const pluginId = "vault-cloak";
const mode = process.argv[2];
const prod = mode === "production";
const selftestOnly = mode === "selftest";

function collectInstallVaults() {
  const vaults = [join(root, "test-vault")];
  const localRoot = join(root, "local");
  if (!existsSync(localRoot)) {
    return vaults;
  }
  for (const name of readdirSync(localRoot)) {
    const candidate = join(localRoot, name);
    if (!statSync(candidate).isDirectory()) {
      continue;
    }
    if (existsSync(join(candidate, ".obsidian"))) {
      vaults.push(candidate);
    }
  }
  return vaults;
}

function installIntoLocalVaults() {
  const files = ["main.js", "manifest.json", "styles.css"];
  for (const vault of collectInstallVaults()) {
    const dest = join(vault, ".obsidian", "plugins", pluginId);
    mkdirSync(dest, { recursive: true });
    for (const file of files) {
      const from = join(root, file);
      if (existsSync(from)) {
        copyFileSync(from, join(dest, file));
      }
    }
  }
}

const copyToVaults = {
  name: "install-into-local-vaults",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) {
        installIntoLocalVaults();
      }
    });
  },
};

const pluginOptions = {
  banner: { js: banner },
  entryPoints: [join(root, "src", "main.ts")],
  bundle: true,
  loader: { ".md": "text" },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: join(root, "main.js"),
  minify: prod,
  plugins: [copyToVaults],
};

const selftestOptions = {
  entryPoints: [join(root, "src", "selftest.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: join(root, "build", "selftest.cjs"),
};

if (selftestOnly) {
  await esbuild.build(selftestOptions);
  process.exit(0);
}

if (prod) {
  await esbuild.build(pluginOptions);
  await esbuild.build(selftestOptions);
  process.exit(0);
}

const context = await esbuild.context(pluginOptions);
await context.watch();
